Repository leannedavid/prism-frontend, pull requests merged in 2018-04, with the labels that each got.

#50 Initial Review Component
  package-lock.json
  src/app/document/document.component.html
  src/app/document/document.component.ts
  src/app/models/user-response.model.ts
  src/app/review/review.component.html
  src/app/review/review.component.ts
  src/app/review/review.service.ts
Labels: implementation

#55 Fix program component date handling
  src/app/colleges/departments/programs/program.service.ts
  src/app/colleges/departments/programs/programs.component.html
  src/app/colleges/departments/programs/programs.component.ts
Labels: bug

#73 Minor style changes preparing for production
  src/app/layout/private/private.component.html
  src/app/login/login.component.css
  src/app/settings/settings.component.css
Labels: enhancement

#74 External upload
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/document/document.component.html
  src/app/document/document.component.ts
  src/app/document/document.service.ts
  src/app/external-upload/external-upload.component.css
  src/app/external-upload/external-upload.component.html
  src/app/external-upload/external-upload.component.spec.ts
  src/app/external-upload/external-upload.component.ts
  src/app/external-upload/external-upload.service.spec.ts
  src/app/external-upload/external-upload.service.ts
  src/app/layout/public/public.component.css
  src/app/layout/public/public.component.html
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/models/external-upload.model.ts
Labels: implementation

#77 Review Archive
  src/app/dashboard/dashboard.component.html
  src/app/models/review.model.ts
  src/app/review-list/review-list.component.css
  src/app/review-list/review-list.component.html
  src/app/review-list/review-list.component.ts
Labels: implementation

#85 Reimplement review list backend and use type unions
  src/app/calendar/calendar.component.ts
  src/app/colleges/colleges.component.ts
  src/app/colleges/departments/department.component.ts
  src/app/committee/committee.component.ts
  src/app/document/document.component.ts
  src/app/group-manager/group-manager.component.ts
  src/app/models/college.model.ts
  src/app/models/comment.model.ts
  src/app/models/department.model.ts
  src/app/models/document.model.ts
  src/app/models/event.model.ts
  src/app/models/external-upload.model.ts
  src/app/models/group.model.ts
  src/app/models/program.model.ts
  src/app/models/review.model.ts
  src/app/models/review_node.model.ts
  src/app/models/user.model.ts
  src/app/review-list/review-list.component.html
  src/app/review-list/review-list.component.ts
  src/app/review/review.component.ts
Labels: enhancement

#90 Review list fixes
  src/app/review-list/review-list.component.html
  src/app/review-list/review-list.component.ts
  src/app/shared/shared.service.ts
  src/app/user-selector/user-selector.component.ts
Labels: bug

#95 Fix root user handling
  src/app/review-list/review-list.component.ts
  src/app/shared/shared.service.ts
Labels: bug
